[package]
name = "lotus-client"
version = "0.1.0"
authors = ["Sylvain Milan <milan.sylvain@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
lotus-common = { path = "../common" }
wasm-bindgen = "0.2"