[package]
name = "lotus-server"
version = "0.1.0"
edition = "2018"

[dependencies]
lotus-common = { path = "../common" }
rand = "0.8"
getrandom = { version = "0.2", features = ["js"] }
sha1 = "0.6"
base64 = "0.13"