[package]
name = "lotus-common"
version = "0.1.0"
authors = ["Sylvain Milan <milan.sylvain@gmail.com>"]
edition = "2018"

[dependencies]
lotus-serializable-derive = { path = "../serializable_derive" }
rand = "0.8"
# wasm-bindgen = "0.2"
getrandom = { version = "0.2", features = ["js"] }